### ISSUE TITLE
I can run on my iPhone but can't successfully compiled on the simulator.

### ISSUE THREAD

**Issue by SilverMQL** [beeware/Python-Apple-support#115]
**Describe the bug**
See above.

**To Reproduce**
1、Download the tag 3.9-b1 —— Python-3.9-iOS-support.b1.tar.gz
2、Create a demo project , drag the unzipped files into the project, select create folder references
3、Add the necessary libraries
4、Run.

**Screenshots**
<img width="708" alt="截屏2021-03-03 20 25 32" src="https://user-images.githubusercontent.com/5146467/109805782-d2c79f80-7c5e-11eb-8a3a-b4b365d310d6.png">

**Environment:**
Xcode 12

**Comment by freakboy3742** [comment]
If you're getting errors about "CoreFoundation" and "UIKit" there's something fundamentally wrong with your project. Those are base iOS libraries; they're not "modules" to be built. 

I'm not sure what "Create a demo project" entails; but I suspect the issue lies there, not the support package. The Briefcase template project, for example, works fine with the published 3.9-b1 support package.

Closing on the basis that the issue appears to be in user-space, not with the support package.
