### ISSUE TITLE
Cann't build numpy-iOS for Xcode 12 or later using repository 3.6 and 3.7

### ISSUE THREAD

**Issue by mamunabcoder** [beeware/Python-Apple-support#129]
Downloaded the below repository:
https://github.com/beeware/Python-Apple-support/tree/3.6
https://github.com/beeware/Python-Apple-support/tree/3.7

Downloading the patch set from git server, following the below process to build support packages and numpy-iOS using Makefile putting the below command into terminal.

Updating the Makefile from below references for Xcode compatibility
https://github.com/OtoJig/Python-Apple-support/commits/3.7

From the above pull request I have updated the Makefile, Makefile.numpy and patch.numpy file, then following used to build the support packages and app_packages.

$ make all or make iOS

Even build the numpy-iOS using Makefile command:
$ make numpy or make numpy-iOS 

After completing the above all process, We finally found the root cause of the Makefile scripting command. Makefile build can’t generate the python folder inside the build MacOS folder. Below beware numpy build script error:

Try to understand the script ###########################################################################
Compiling Python Libraries with binary components ###########################################################################
HOST_PYTHON=$(CURDIR)/build/macOS/python/bin/python3
HOST_PIP=$(CURDIR)/build/macOS/python/bin/pip3

Not found the solution for makefile script for numpy-ios installation

HOST_PYTHON=$(CURDIR)/build/macOS/python/bin/python3
HOST_PIP=$(CURDIR)/build/macOS/python/bin/pip3

 **_build folder python is not generated_**

**Comment by JohnyLisir** [comment]
I have the same problem, Xcode12 ,macOS 12.0.1, 
use https://github.com/beeware/Python-Apple-support/tree/3.7
and do you have a solution?

**Comment by dalcacer** [comment]
It seems like the script expects `HOSTPYTHON` to be situated at `/Python-Apple-support/build/macOS/python` .
As a workaround you can link `/Python-Apple-support/build/macOS/Python-3.9.6-macOS` to `/Python-Apple-support/build/macOS/python` .

Odd enough, the actual Python binary is then located under `Python-Apple-support/build/macOS/python/dist/bin/python3` instead of `Python-Apple-support/build/macOS/python/bin/python3` . So you would have to adjust the `makefile:556` and `makefile:557` to correct these - I wonder why `Python-iOS` build in the first place.

**Comment by freakboy3742** [comment]
Closing as we're deprecating the numpy build system provided by this project, in favour of a more comprehensive approach to support binary packages.
