### ISSUE TITLE
 Python exception: No module named 'math'

### ISSUE THREAD

**Issue by eldare** [beeware/Python-Apple-support#170]
**Describe the bug**
`import math` throws the following error:  `Python exception: No module named 'math'`

**To Reproduce**
1. `setenv("PYTHONHOME", "<python-stdlib location>", 1)`
2. `setenv("PYTHONPATH", "<python-stdlib location>", 1)`
3. `Py_Initialize()`
4. Using PythonKit: `Python.import("sys")` -> Works
5. `Python.import("os")` -> Works
6. `Python.import("pathlib")` -> Works
7. `Python.import("math")` -> Exception

**Expected behavior**
It should be possible to `import math`.

**Screenshots**

<img width="1490" alt="Screen Shot 2022-12-01 at 22 25 22" src="https://user-images.githubusercontent.com/40336237/205152526-3ada1df7-ff9c-4f75-8d86-38a8dd6c230e.png">

**Environment:**
 - Operating System: MacOS Monterey 12.6
 - Python version: Python-3.11-macOS-support.b1
 - Software versions:
   - Xcode: 14.0

**Additional context**
I've tried to use `Python-3.10-macOS-support.b6`, only to the get the same exception.

I tried to make sure the source of the issue is not coming from PythonKit.
I used the local Python 3.11 on the mac (by removing the MacOS App's Sandbox + "Disable Library Validation"). It was able to import math with issues.

Thank you

**Comment by freakboy3742** [comment]
I believe the issue is your PythonKit configuration. The math module definitely exists, and can be used successfully (verified by both the [Python-support-testbed app](https://github.com/beeware/Python-support-testbed)), and manual testing by adding `import math` to a Briefcase test project.

From what you've described, the interpreter can't find your lib-dynload path. `os` and `pathlib` are backed by a `os.py` and `pathlib.py` respectively; math is a binary module in the `lib-dynload` directory. `PYTHONHOME` needs to point to a base folder that contains `lib/python3.X`; and/or `PYTHONPATH` needs to include the `lib-dynload` folder. If nether of those things are true, then the interpreter won't be able to find the binary module to load at runtime.

**Comment by eldare** [comment]
@freakboy3742 Thank you for the reply. You're right `lib-dynload` was missing from `PYTHONPATH`. I've added it, and I'm getting a more specific error `python-stdlib/lib-dynload/math.cpython-311-darwin.so' not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.)`

I need to find a way to sign this file with my TeamID.

I wonder if I can move python-stdlib inside the Python.xcfreamework to get it signed automatically?

Thank you

**Comment by freakboy3742** [comment]
@eldare FWIW: We're not actively supporting other use cases external to Briefcase at present, but if someone were to write up a usage guide as a PR, I wouldn't reject the PR.

**Comment by eldare** [comment]
I understand. Thank you again :)

**Comment by eldare** [comment]
@freakboy3742 as suggested, I've submitted a PR with a detailed usage guide.
