### ISSUE TITLE
How to embed python-source library

### ISSUE THREAD

**Issue by alpdigitech** [beeware/Python-Apple-support#3]
Hello. Is there a file where library names (ex. nltk - pure python) can be added so that they are also embedded in the built python framework?

**Comment by freakboy3742** [comment]
If the module is *Pure python*, then it can be installed directly to the app_packages folder in your  (using `pip install -t <path to app_packages> <package name>`).

If there's a compiled component, it's a little more complex because the binary components need to be integrated into the overall build process. This can be done at two levels:

* In the support library, as a binary component compiled in the same way that libraries like OpenSSL are currently managed
* By integrating the source components into your XCode build file.

I'm hoping that [Briefcase](https://github.com/pybee/briefcase) will make the second part easier in the not-too-distant future; but for the moment, you need to manage the process manually.

**Comment by gm6379** [comment]
I tried to install numpy using the above method into my `app_packages` directory, however when I run the code I receive this error:

```
ImportError: 
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.
```

**Comment by freakboy3742** [comment]
@gm6379 As noted in my previous reply, you can only use *pure python* modules at the moment. Numpy isn't a pure python module - it contains compiled components. You will need to add the source code components of numpy to your XCode project.

**Comment by zoudike** [comment]
hi,my python file have "import cv2" and "import numpy",but i can't get a module with "PyImport_ImportModule",i need how to do?

**Comment by CJRobey** [comment]
tinynumpy is a pure python numpy compliant package. I'm trying it out now as a substitute.

**Comment by freakboy3742** [comment]
Closing as the original question has been answered.
