### ISSUE TITLE
Minimal Python

### ISSUE THREAD

**Issue by gmli** [beeware/Python-Apple-support#49]
Hi,

I would like to use Python as a scripting language on Android and iOS, to reuse lots of code. On Android libpython + std lib is no more than 6Mo, but with Python-Apple-Support by default the size for iOS is insanely huge.

Is there a way to build a minimal Python distribution (without openssl, bzip, sqlite, etc) ? 
Thanks in advance.

**Comment by gmli** [comment]
I've modified the Makefile to remove all unwanted lib (for me) : openssl, sqlite, etc. I've also remove some libs from Setup.embedded.

Now the libs for arm(v7 and 64, I've added support for v7 in the makefile) weight something like 40mo each. So armv7+64 and simulator_x86 are now 108Mo. 

It's better but far from 3Mo for the crystax pre-compiled libpython.

Any idea ?

**Comment by dimaqq** [comment]
3MB is normal for stripped libpython.so (without any python module or .so modules).
All the .pyc files take ~24MB;
All .py files take more, but they compress better, zip of all py files takes ~7MB.

Here's a practical plan, on the balance of size and complexity:
* drop pyc files altogether, set environment variable not to make them on module load
* find the smallest subset .py files you need
* pack them all in a single .zip
* either identify all the .so files you need or try to link statically

If that's still too large, perhaps you should look at micropython? :snake: :+1: 
I'm not kidding -- there was a conference talk about micropython as linux init process -- it starts very fast (great for mobile apps!), runs in fixed amount of memory (arguable, but could be great), etc.

**Comment by freakboy3742** [comment]
The 108MB download is an older build; the most recent Python3.6 build (b7) is a 49MB download; libPython.a is 64MB uncompressed, which includes all the binary components for OpenSSL, BZip etc, for both ARM64 and x86_64 (the most recent builds dropped support for ARMv6, ARMv7 and ARMv7s).

I haven't done any debug stripping either - so that binary has a lot of information that can be discarded (and *will* be automatically discarded) by the iOS compilation process. 

Android also has the advantage that it only needs to support one architecture - it doesn't have a "Fat" binary format like iOS. The "real" size for iOS is at least half what the download reports.

You can see this if you build an app - the final image will be a lot smaller than the support library. The Travel Tips app that is in the iOS app store is a 49MB IPA file, which includes the "full" Python support library, plus all the code and assets for the final app.

That said, I agree that it would be nice for the support package (and the resultant binaries) to be smaller. 

One of the major reasons the iOS libPython is large is because it's a *static* library. iOS doesn't allow dynamic loading of libraries, so *all* the compiled modules are included in libPython.a. I'm guessing your 3MB Android library is hiding *most* of it's size in the site-packages directory in `.so` files. So Android's Python isn't actually smaller - it's just packaged differently and carrying it's weight somewhere else. 

However, even with that, I'm surprised it's 3MB. libPython3.6m.a on a macOS build (which is dynamically loaded, on a single architecture) is 10MB. I'm not sure what else the Android build is stripping out to get it's reduced size.

Putting together a nicer mechanism for coordinating a "stripped" build (like the approach you've described) is on my wish list. Removing parts of the standard library (both binary and pure Python) that aren't being used is the obvious way to make the builds smaller.

**Comment by gmli** [comment]
The 108Mo is my compiled version of the 3.7 branch.

MicroPython is a good idea perhaps, I was thinking of it before testing Python-Apple-Support. But I prefer testing this project before trying MicroPython :)

I don't really know how to strip down the build. In the Setup.embedded I've added this line : 

*disabled*

And then added some modules. Is this the right way to do it ? I ask because the size seems to be reduced, but I always see the « disabled » modules in each libpython.a (for each platform).

I don't know either was to put in module names, the names used to import them in a Python script ? If I want to remove almost all, and add a kind of whitelist is it possible ? (I'm not really versed in Makefile and CPython compiling sorry…).

Maybe we could have a separate Makefile for a minimal Python without any module, and people could add them one by one if wanted.

Thanks for your replies.

**Comment by gmli** [comment]
Here is my current Makefile : 
https://gist.github.com/gmli/314e0792e2526cc1b2356f0c5d438083

I think most of the work now is in Setup.* to strip Python down to the bare minimum.

**Comment by freakboy3742** [comment]
@gmli Thanks for documenting that procedure. 

The end goal would be to have a relatively simple configuration mechanism (e.g., a single file you can drop somewhere that just lists the modules you want/don't want) rather than having to modify complex Makefiles or Setup.embedded scripts.

**Comment by gmli** [comment]
I'm making some progress :

I build the whole thing (with the Makefile on gist, and a Setup.embedded in the patch folder full of disabled modules). The libpython3.7m.a of arm64 is 26Mo.

In the arm64 folder, I do a "make clean" and then this configure : 

./configure CC="xcrun --sdk macosx clang -arch x86_64 --sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.8" LD="xcrun --sdk macosx clang -arch x86_64 --sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.8" --host=x86_64-apple-ios --build=x86_64-apple-darwin17.6.0 --without-doc-strings --enable-ipv6 --without-ensurepip ac_cv_file__dev_ptmx=no ac_cv_file__dev_ptc=no

Then a "make". In theory the result should be the same. But now the libpython3.7m.a is 11Mo. I don't really understand why. Is my configure erroneous ?

**Comment by gmli** [comment]
Yes my configure was faulty, wrong arch. Nevertheless, it's hard to go under 20Mo, even with disabling almost everything. I don't understand how Crystax NDK made it so low.

**Comment by gmli** [comment]
With (almost) all disabled, libpython.a for MacOS is 11Mo while libpython.a for armv7 and arm64 are 24Mo.
Do you have any hint on why so must difference ?

**Comment by gmli** [comment]
The difference was due to -febmed-bitcode on iphoneos archs : 24Mo -> 9Mo.

I can know work on well defined Makefile and Setup.

**Comment by freakboy3742** [comment]
Ah - in which case, we have a problem because - because AFAIK, that flag is required to make binaries that are acceptable to the App Store. The binary will work fine in the simulator, but if you archive the build for submission, it will be rejected. You can check this by building an ad-hoc build - it goes through the same packaging process, but without actually needing to submit to the app store.

**Comment by dimaqq** [comment]
IMO you needn't worry about bitcode size overhead, as the actual binary that someone's phone or watch pulls from the app store is not going to contain it, instead, end-user gets an "optimized" version for their arch only. At least that's the promise :).

**Comment by gmli** [comment]
Yes, I've read someone saying that on a forum. Nice.

**Comment by freakboy3742** [comment]
I'm going to close this ticket as there is now a solution to this problem.

As of 3.8-b10/3.9-b8/3.10-b4/3.11-b0, the support package uses dynamic loaded modules, rather than statically linking the binary modules into `libPython.a`. This means the code for the `bz2`, `lzma`, and `ssl` modules are all independent files. If your application doesn't require these files, they can be safely deleted, and your application will be substantially smaller. The only thing that is "mandatory" is the core set of frozen modules that the Python interpreter requires - modules like `sys` and `importlib`.

Briefcase 0.3.10 (due to be released in the next week or so) includes additional functionality that allows you to specify files that you want to be purged from your app, so you can specify a pattern of files to delete from your app at time of packaging.
