### ISSUE TITLE
Writing files to IOS

### ISSUE THREAD

**Issue by mrwulff** [beeware/Python-Apple-support#69]
So my program runs fine on the simulator, but when I run it on the iphone it errors out because im writing to the directory of the executable which is sandboxed.  And apple wants you to write to the Documents folder instead.  Is there any way of doing this without using some form of Rubicon?

**Comment by freakboy3742** [comment]
There isn't a built in utility - but we definitely need one. Every device (mobile or desktop) has range of locations where files/content can be stored, including (but not limited to):

* application-supplied files
* temporary files
* cache content
* user content

The actual file locations, however, vary from platform to platform. We need to provide a high-level API for providing those file locations.

**Comment by mrwulff** [comment]
I have been trying to make it work with rubicon bindings but am gettings nowhere.  Can you point me in the right direction?

**Comment by freakboy3742** [comment]
The thing is, it's not really a "Rubicon" thing per se - it's a low level iOS API that you need to find. iOS provides locations for storing files; Rubicon is only needed so that you can invoke those APIs. 

I don't know the iOS calls that are needed - I'm guessing they're going to be related to Bundle (and the application's mainBundle in particular). I found [this document](https://developer.apple.com/icloud/documentation/data-storage/index.html) in a quick search, but more research will be required.

**Comment by freakboy3742** [comment]
Closing since this isn't a problem with the support package; the issue lies in how the support package is being used.
