### ISSUE TITLE
Linking non-standard Python libraries in iOS

### ISSUE THREAD

**Issue by rakeeb123** [beeware/Python-Apple-support#75]
I am currently working on an iOS app with my company where we are already using Python Apple Support successfully to run standard Python code. However, we need to import the python-socketio library in our project. 

How would we go about linking a library like this one similar to how OpenSSL is built and imported from the Support directory? I've tried looking around, but haven't found yet and would really appreciate a step in the right direction!

**Comment by freakboy3742** [comment]
It depends if it's an external library, or a binary module. 

If it's an external library (like OpenSSL), then you need to work out the compiler settings needed to target each platform of interest, then build a Fat library (using the lipo tool). The Makefile for Python-Apple-Support will give you the broad strokes of what is required - look at the similarities for how xz, bzip2 and OpenSSL are compiled. Then, you add those binaries to your XCode project.

If it's a binary module, the process is a little more complicated. You need to get the source code for the C module, and either add it to your XCode project directly, or build it as a static library. That will also involve forcing the load of the C module during the instantiation of the iOS app. Look at how Numpy is supported for guidance on this.

The process has historically been complicated because iOS didn't allow dynamic libraries (.so files), which is how Python manages C modules. However, I've seen some suggestion that this restriction may have been lifted. I'd love to have the time to explore this, but I'm unlikely to any time soon. If someone wanted to look into this...

**Comment by ColdGrub1384** [comment]
An example with `dlopen`: https://github.com/ColdGrub1384/Pyto/blob/master/Pyto/main.m
SO files can be placed inside frameworks with an `Info.plist`

**Comment by freakboy3742** [comment]
Closing as the original question has been answered
