### ISSUE TITLE
upgrading openssl

### ISSUE THREAD

**Issue by siege098** [beeware/Python-Apple-support#92]
I am trying to use some code that will verify an app store receipt from apple.  The code uses openSSL version 1.1.1 it appears you are using version openSSL 1.0 in your package.  The problems appear to be related to things referenced in the header file 'asn1_locl.h (it's not present in the old version)'.  Any ideas on how hard it is to upgrade the openSSL, or am I stuck trying to get it working with 1.0?

**Comment by freakboy3742** [comment]
Unfortunately, [Python 3.5 and 3.6 are stuck on OpenSSL 1.0.2](https://bugs.python.org/issue32947); upgrading those versions to use OpenSSL 1.1.1 will be very difficult. 

The good news is that, Python 3.7 and 3.8 already use OpenSSL 1.1.1. 

If you have a package that specifically requires Open SSL 1.1.1, I would suggest moving to an updated Python version.

Closing this ticket on the basis that there's not much we can do, as the underlying problem is upstream in Python.
