### ISSUE TITLE
Problem when uploading binary to AppStore.

### ISSUE THREAD

**Issue by fangyuxi** [beeware/Python-Apple-support#93]
![2351591984961_ pic_hd](https://user-images.githubusercontent.com/1756038/84533140-1d446d00-ad1a-11ea-88c2-5db34fb2a927.jpg)
![2361591985009_ pic_hd](https://user-images.githubusercontent.com/1756038/84533142-1d446d00-ad1a-11ea-9699-f8607bde7ae9.jpg)

I know this is because Python.Framework is included in the copy bundles resources, but if I don’t do this, then there is no way to specify the root directory of the python (such as the code screenshot in the example image).

Can I include the source code of python to run in the project, but not the compiled python binary?

Thank you
Best Regards

**Comment by ColdGrub1384** [comment]
Instead of `mainBundle`, use this to get the path of a resource inside a framework: https://developer.apple.com/documentation/foundation/nsbundle/1411929-bundlewithidentifier?language=objc

**Comment by freakboy3742** [comment]
I don't know where you're getting a ``Python.framework`` from, but it wasn't produced by recent builds of this project. If you're using an older build (such as the 2.7 build), those configurations are no longer supported - partly because they weren't compatible with the App Store, but also because Python 2 has reached End Of Life and is no longer supported.
